on: 
    workflow_call:
      inputs:
        tag:
          description: 'The version tag to use for stamping build artifacts and naming generated archives'
          required: true
          type: string
        prerelease:
          description: 'Set to true if published build is a prerelease'
          type: boolean
          required: true
      secrets:
        PACKAGE_USER:
          required: true
        PACKAGE_PAT:
          required: true
env:
  DOCKER_REPO: ghcr.io/${{ github.repository_owner }}/cxone/cxone-flow
                
jobs:
  publish-container:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

      - name: Login to GitHub Container Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ghcr.io
          username: ${{ secrets.PACKAGE_USER }}
          password: ${{ secrets.PACKAGE_PAT }}

      - name: Fetch Code @ tag ${{ inputs.tag }}
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
        with:
          ref: refs/tags/${{ inputs.tag }}

      - name: Update version.txt
        run: |
            echo __version__=\"${{ inputs.tag }}\" > _version.py

      - name: Build and Push Docker Image
        run: |
          BRIEFTAG=${{ inputs.tag }}
          docker build -f docker/Dockerfile -t $DOCKER_REPO:$BRIEFTAG .
          [ ${{ inputs.prerelease }} = false ] && docker tag $DOCKER_REPO:$BRIEFTAG $DOCKER_REPO:latest || :
          docker push --all-tags $DOCKER_REPO
  

  compile-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Code @ tag ${{ inputs.tag }}
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
        with:
          ref: refs/tags/${{ inputs.tag }}
        
      - name: Edit manual's version stamp
        run: echo ${{ inputs.tag }} > manual/version.tex

      - name: Build PDF Manual
        uses: xu-cheng/latex-action@f1ca82cbed861b3534e2997dd584944f55b884ed
        with:
          root_file: manual/cxone-flow.tex
          work_in_root_file_dir: true

      - name: Upload manual
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b
        with:
          name: manual-${GITHUB_RUN_NUMBER}
          path: manual/cxone-flow.pdf
  
      - name: Build PDF Release Notes
        uses: xu-cheng/latex-action@f1ca82cbed861b3534e2997dd584944f55b884ed
        with:
          root_file: release_notes/release_notes.tex
          work_in_root_file_dir: true

      - name: Upload release notes
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b
        with:
          name: release-notes-${GITHUB_RUN_NUMBER}
          path: release_notes/release_notes.pdf

  resolver-agent-deb-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Code @ tag ${{ inputs.tag }}
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
        with:
          ref: refs/tags/${{ inputs.tag }}

      - name: Update version.txt
        run: |
            echo __version__=\"${{ inputs.tag }}\" > _version.py

      - name: Build deb package
        run: agent_packages/resolver/debian/build-package.sh ${{ inputs.tag }}

      - name: Upload deb amd64 package
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b
        with:
          name: deb-amd64-${GITHUB_RUN_NUMBER}
          path: agent_packages/resolver/debian/*.deb

  publish-release:
    runs-on: ubuntu-latest
    needs: [publish-container,compile-manual,resolver-agent-deb-amd64]
    steps:
      - name: Make release text
        run: |
          echo "# CxOneFlow ${{ inputs.tag }}" > release.md
          echo The CxOneFlow ${{ inputs.tag }} Server is available in a container: >> release.md
          echo '```' >> release.md
          [ ${{ inputs.prerelease }} = false ] && echo "docker pull $DOCKER_REPO:latest" >> release.md || :
          echo "docker pull $DOCKER_REPO:${{ inputs.tag }}" >> release.md
          echo '```' >> release.md
          echo The CxOneFlow Resolver Agent is an optional component for running SCA Resolver prior to a scan.  It >> release.md
          echo can be downloaded as an installer package appropriate for supported operating systems. >> release.md

      - name: Download manual
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
        with:
          name: manual-${GITHUB_RUN_NUMBER}

      - name: Download release notes
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
        with:
          name: release-notes-${GITHUB_RUN_NUMBER}

      - name: Rename documentation artifacts
        run: |
          mv cxone-flow.pdf cxone-flow-manual-${{ inputs.tag }}.pdf
          mv release_notes.pdf cxone-flow-release-notes-${{ inputs.tag }}.pdf

      - name: Download deb-amd64
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
        with:
          name: deb-amd64-${GITHUB_RUN_NUMBER}

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@6c75be85e571768fa31b40abf38de58ba0397db5
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: ./*.pdf, ./*.deb
          bodyFile: release.md
          name: ${{ inputs.tag }}
          prerelease: ${{ inputs.prerelease }}
          tag: ${{ inputs.tag }}


  artifact-cleanup:
    runs-on: ubuntu-latest
    needs: [publish-release]
    steps:
      - uses: geekyeggo/delete-artifact@9d15d164b1dcd538ff1b1a2984bc2c0240986c3b
        with:
          name: |
            release-notes-${GITHUB_RUN_NUMBER}
            manual-${GITHUB_RUN_NUMBER}
            deb-amd64-${GITHUB_RUN_NUMBER}
        
